### PR TITLE
epl-sup-tree plugin

### LINKED ISSUE #9: epl-sup-tree plugin
@arkgil [said](https://github.com/erlanglab/erlangpl/issues/10#issuecomment-284188068) he's experimenting with this view. The idea is to have supervisor tree, the similar to Erlang observer.

Idea is to implement it with [http://sigmajs.org/](http://sigmajs.org/) library because it has look we're interested in.

Plugin should export React component, reducer and socket listeners if is listening to any.

### PR DESCRIPTION
**Pull request by Baransu**
Resolve #9. Creates `epl-sup-tree` plugins.
 * [x] application tree graph
 * [x] OTP applications list
 * [x] selecting node -> node info
 * [x] toggling specific OTP applications on graph
 * [x] better graph rendering on route change
 * [x] show loader when no data to display yet
 * [x] better side panel (applications list, node info) styling

### CODE REVIEW

**Comment by Baransu** [comment]
@arkgil I'm working towards merge. It's feature complete and only need styling and some polish. If you can check it out and give me some review it would be awesome. 

If I'll have enough time should be merged by Friday.

**Comment by michalslaski** [comment]
I tried it and it looks great. I appreciate you are trying to stick to one palette of colours across all views.

Thank you so much!

**Comment by Baransu** [comment]
If you have any idea how can I make it better, let me know.

**Comment by arkgil** [comment]
Amazing!

**Comment by Baransu** [comment]
@michalslaski @arkgil Looking for your review. How it feels and how it works for you?

**Pull request merged**
