### PR TITLE
About page basic content

### LINKED ISSUE #7: Add content to /about view
This view should contain some copyright info, change log, contact, webpage, link to documentation, etc.

It's important because it's written in Elm as out example how to integrate Elm within `erlangpl`. Being simple static view it's still value to have it written in Elm to show how any Elm view can be written.

### PR DESCRIPTION
**Pull request by Baransu**
Resolve #7 
This is only basic content to fill this page with some informations. Future plan is to support markdown rendering and add FAQ, Contribution Guide, maybe some setting user can adjust.

### CODE REVIEW

**Comment by michalslaski** [comment]
It's good time to update the bootstrap script to include erlangpl-ui build. It should help you with testing. I hope to fix it soon.

**Comment by Baransu** [comment]
Should I take care of bootstrap script?

**Comment by michalslaski** [comment]
Sure.

**Comment by Baransu** [comment]
I'm going to add `erlang-ui` as `erlangpl` submodule.

**Comment by Baransu** [comment]
I've tested it with latest version of `erlangpl`. Going to merge and release `0.1` version. 

/cc @michalslaski

**Pull request merged**
