### PR TITLE
Update traffic to new Vizceral version

### LINKED ISSUE #29: Nothing is displayed for single nodes in the `traffic`
When going to `/traffic` in Chrome and Safari with a single node running there is not visual representation of that node (included DevTools console in hopes that would help):

screen shot 2017-04-03 at 10 22 40 pm

If I mouse around I am able to get the hand icon and click into the nothingness and get into the traffic view for that node.

In Firefox it doesn't get past the loading image and has an error in the console:

screen shot 2017-04-03 at 10 33 52 pm

I'm not familiar with browser support of WebGL so I'm not which browser was best to check with.

```
> node --version
v6.9.1
> elm --version
0.18.0
```

Please let me know if I am missing anything or could provide more information.

### PR DESCRIPTION
**Pull request by baransu**
Fixes: #29
Few days ago I've send [PR](https://github.com/Netflix/vizceral/pull/59) to Vizceral. Proposed changes were merged and released as 4.4.0. 

* fixed denamification for source node name
* removed fake click on entryNode
* bumped `vizceral-react` version to 4.4.0

### CODE REVIEW

**Comment by Baransu** [comment]
Going to release version 0.3 after this got merged.

**Review by michalslaski — APPROVED** [review]

**Comment by arkgil** [comment]
Everything looks great, but I have one suggestion: could we make color of outgoing particles different than incoming ones? It's hard to see what's going on if there are a lot of them.

**Comment by Baransu** [comment]
We can treat outgoing messages as warrnings which will make them yellow. There should be another way to do it but I'm not sure right now.

**Comment by arkgil** [comment]
I see. I think it's fine, because we don't specify something like "warning" message or traffic (yet).

**Comment by michalslaski** [comment]
I would worry more about incoming traffic than outgoing. The observed node is our concern. The more traffic it gets, the more load it need to handle. Does incoming yellow traffic look good? I can't test right now myself.

**Comment by Baransu** [comment]
I'll test later today and post to YouTube so you can check how it looks :)

**Comment by Baransu** [comment]
@michalslaski Here you can see example with Mnesia: https://youtu.be/-AvscsVSyck
There is little flickering with bi-directional traffic but it's easier to understand than our previous version.

**Comment by michalslaski** [comment]
@Baransu thanks for sharing the video. Do you know why the yellow traffic sometimes appears in front of the blue one and sometimes behind it? I don't want to be too picky, but I'm worried people will not focus on what the visualization is trying to explain, instead they will focus on the "special effects".

**Comment by Baransu** [comment]
It may be because of texture overlaping on the z-axis. I'll to look into Vizceral how they handle that.

**Comment by Baransu** [comment]
I've spend around 3 hours debugging Vizceral code but I have no idea how to come up with good solution to this problem. I've also created [issue](https://github.com/Netflix/vizceral/issues/62) describing this problem.

**Comment by Baransu** [comment]
@michalslaski should we keep that flickering and move on working to Vizceral fix or should we make all messages the same color?

**Comment by michalslaski** [comment]
@Baransu I suggest to keep the same color until the "special effect" is fixed.

Do I understand it correctly that if we would merge this PR we have:
* animation indicates ingress/egress traffic with direction of particles stream
* RPS indicates how many messages has been sent from the observed node
* RPS% indicates what percentage of the overall traffic generated by the observed node was received

**Comment by Baransu** [comment]
Correct

**Comment by Baransu** [comment]
I'm merging it and releasing version 0.3

**Pull request merged**
